build_path = "src/Enums.luau"
use_union_types_for_tree = false
use_union_types_for_export = true

[enums]

SoundType = [
	"hero_simple_celebration_02",
	"navigation_cancel",
	"ui_tap_variant_03",
	"alert_error_03",
	"notification_ambient",
	"state_change_confirm_up",
	"ringtone_minimal",
	"hero_decorative_celebration_01",
	"navigation_transition_right",
	"hero_decorative_celebration_02",
	"alert_simple",
	"ui_loading",
	"notification_decorative_01",
	"notification_high_intensity",
	"navigation_backward_selection_minimal",
	"navigation_unavailable_selection",
	"ui_unlock",
	"notification_decorative_02",
	"navigation_hover_tap",
	"ui_tap_variant_01",
	"ui_tap_variant_04",
	"ui_tap_variant_02",
	"alert_error_02",
	"alarm_gentle",
	"ui_refresh_feed",
	"hero_simple_celebration_01",
	"hero_decorative_celebration_03",
	"hero_simple_celebration_03",
	"alert_high_intensity",
	"state_change_confirm_down",
	"navigation_transition_left",
	"notification_simple_01",
	"navigation_forward_selection",
	"navigation_selection_complete_celebration",
	"ui_camera_shutter",
	"navigation_forward_selection_minimal",
	"notification_simple_02",
	"navigation_backward_selection",
	"ui_lock",
	"alert_error_01",
]
FontType = [
	"DisplayLarge",
	"DisplayMedium",
	"DisplaySmall",
	"HeadlineLarge",
	"HeadlineMedium",
	"HeadlineSmall",
	"TitleLarge",
	"TitleMedium",
	"TitleSmall",
	"BodyLarge",
	"BodyMedium",
	"BodySmall",
	"LabelLarge",
	"LabelMedium",
	"LabelSmall",
]
ButtonStateType = ["Enabled", "Disabled", "Hovered", "Focused", "Pressed"]
SchemeType = ["Light", "Dark"]
CustomColorType = [
	"Custom",
	"OnCustom",
	"CustomContainer",
	"OnCustomContainer"
]
SelectionState = [
	"Selected",
	"Unselected"
]
ColorRoleType = [
	"Primary",
	"OnPrimary",
	"PrimaryContainer",
	"OnPrimaryContainer",
	"Secondary",
	"OnSecondary",
	"SecondaryContainer",
	"OnSecondaryContainer",
	"Tertiary",
	"OnTertiary",
	"TertiaryContainer",
	"OnTertiaryContainer",
	"Error",
	"OnError",
	"ErrorContainer",
	"OnErrorContainer",
	"Background",
	"OnBackground",
	"Surface",
	"OnSurface",
	"SurfaceVariant",
	"OnSurfaceVariant",
	"Outline",
	"OutlineVariant",
	"Shadow",
	"Scrim",
	"InverseSurface",
	"InverseOnSurface",
	"InversePrimary",
	"SurfaceDim",
	"SurfaceBright",
	"SurfaceContainerLowest",
	"SurfaceContainerLow",
	"SurfaceContainer",
	"SurfaceContainerHigh",
	"SurfaceContainerHighest",
	"SurfaceTint",
]
PaletteType = [
	"Primary",
	"Secondary",
	"Tertiary",
	"Neutral",
	"NeutralVariant",
	"Error",
]
TransitionType = [
	"Emphasized",
	"EmphasizedDecelerate",
	"EmphasizedAccelerate",
	"Standard",
	"StandardDecelerate",
	"StandardAccelerate",
]
TransitionDuration = [
	"Short1",
	"Short2",
	"Short3",
	"Short4",
	"Medium1",
	"Medium2",
	"Medium3",
	"Medium4",
	"Long1",
	"Long2",
	"Long3",
	"Long4",
	"ExtraLong1",
	"ExtraLong2",
	"ExtraLong3",
	"ExtraLong4",
	
]