std = "lints/luau+roblox"
exclude = [
	"out/*", 
	"*.spec.lua",
	"*.spec.luau",  
	"*.remodel.lua", 
	"*.rbxmk.lua",
	"*.d.lua",
	"*.story.lua",
	"*.story.luau",
	"gamework/*", 
	"scripts/*", 
]
[lints]
unused_variable = "allow"
empty_if = "allow"
if_same_then_else = "allow"
